// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.1
// source: api.v1.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Container_Status int32

const (
	Container_NEW      Container_Status = 0
	Container_STARTING Container_Status = 1
	Container_READY    Container_Status = 2
	Container_RUNNING  Container_Status = 3
	Container_STOPPING Container_Status = 4
)

// Enum value maps for Container_Status.
var (
	Container_Status_name = map[int32]string{
		0: "NEW",
		1: "STARTING",
		2: "READY",
		3: "RUNNING",
		4: "STOPPING",
	}
	Container_Status_value = map[string]int32{
		"NEW":      0,
		"STARTING": 1,
		"READY":    2,
		"RUNNING":  3,
		"STOPPING": 4,
	}
)

func (x Container_Status) Enum() *Container_Status {
	p := new(Container_Status)
	*p = x
	return p
}

func (x Container_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Container_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_proto_enumTypes[0].Descriptor()
}

func (Container_Status) Type() protoreflect.EnumType {
	return &file_api_v1_proto_enumTypes[0]
}

func (x Container_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Container_Status.Descriptor instead.
func (Container_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{1, 0}
}

type Calculate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Calculate) Reset() {
	*x = Calculate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Calculate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculate) ProtoMessage() {}

func (x *Calculate) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculate.ProtoReflect.Descriptor instead.
func (*Calculate) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{0}
}

type Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Container) Reset() {
	*x = Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{1}
}

type Calculate_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *Container_Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *Calculate_Request) Reset() {
	*x = Calculate_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Calculate_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculate_Request) ProtoMessage() {}

func (x *Calculate_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculate_Request.ProtoReflect.Descriptor instead.
func (*Calculate_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Calculate_Request) GetParams() *Container_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type Calculate_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Calculate_Response) Reset() {
	*x = Calculate_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Calculate_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculate_Response) ProtoMessage() {}

func (x *Calculate_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculate_Response.ProtoReflect.Descriptor instead.
func (*Calculate_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Calculate_Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Container_Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed  string `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Input string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *Container_Params) Reset() {
	*x = Container_Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container_Params) ProtoMessage() {}

func (x *Container_Params) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container_Params.ProtoReflect.Descriptor instead.
func (*Container_Params) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Container_Params) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *Container_Params) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type Container_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr   string            `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Params *Container_Params `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Status Container_Status  `protobuf:"varint,4,opt,name=status,proto3,enum=Zapuskator.API.v1.Container_Status" json:"status,omitempty"`
}

func (x *Container_Info) Reset() {
	*x = Container_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container_Info) ProtoMessage() {}

func (x *Container_Info) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container_Info.ProtoReflect.Descriptor instead.
func (*Container_Info) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Container_Info) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container_Info) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Container_Info) GetParams() *Container_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Container_Info) GetStatus() Container_Status {
	if x != nil {
		return x.Status
	}
	return Container_NEW
}

type Container_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Container_Request) Reset() {
	*x = Container_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container_Request) ProtoMessage() {}

func (x *Container_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container_Request.ProtoReflect.Descriptor instead.
func (*Container_Request) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Container_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Container_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *Container_Info `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *Container_Response) Reset() {
	*x = Container_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container_Response) ProtoMessage() {}

func (x *Container_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container_Response.ProtoReflect.Descriptor instead.
func (*Container_Response) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Container_Response) GetInfo() *Container_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_api_v1_proto protoreflect.FileDescriptor

var file_api_v1_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x73, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x1a, 0x46, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x1a, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x8b, 0x03, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x1a, 0x32, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0xa4, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x12, 0x3b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x41, 0x50, 0x49, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x3b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x23, 0x2e, 0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x50,
	0x49, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x19, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x41, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x41, 0x50, 0x49, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x45, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49,
	0x4e, 0x47, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x49, 0x4e, 0x47,
	0x10, 0x04, 0x32, 0x9b, 0x02, 0x0a, 0x0d, 0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b, 0x61, 0x74, 0x6f,
	0x72, 0x41, 0x50, 0x49, 0x12, 0x8c, 0x01, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x12, 0x24, 0x2e, 0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x41, 0x50, 0x49, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x5a, 0x61, 0x70, 0x75, 0x73,
	0x6b, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x32, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2c, 0x12, 0x2a, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x7b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x73,
	0x65, 0x65, 0x64, 0x7d, 0x2f, 0x7b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x7d, 0x12, 0x7b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x2e, 0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x5a, 0x61, 0x70, 0x75, 0x73, 0x6b, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x64, 0x7d,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x65, 0x6e, 0x6b, 0x6f, 0x72, 0x65, 0x6e, 0x2f, 0x6d, 0x69, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2d,
	0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_proto_rawDescOnce sync.Once
	file_api_v1_proto_rawDescData = file_api_v1_proto_rawDesc
)

func file_api_v1_proto_rawDescGZIP() []byte {
	file_api_v1_proto_rawDescOnce.Do(func() {
		file_api_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_proto_rawDescData)
	})
	return file_api_v1_proto_rawDescData
}

var file_api_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_proto_goTypes = []interface{}{
	(Container_Status)(0),      // 0: Zapuskator.API.v1.Container.Status
	(*Calculate)(nil),          // 1: Zapuskator.API.v1.Calculate
	(*Container)(nil),          // 2: Zapuskator.API.v1.Container
	(*Calculate_Request)(nil),  // 3: Zapuskator.API.v1.Calculate.Request
	(*Calculate_Response)(nil), // 4: Zapuskator.API.v1.Calculate.Response
	(*Container_Params)(nil),   // 5: Zapuskator.API.v1.Container.Params
	(*Container_Info)(nil),     // 6: Zapuskator.API.v1.Container.Info
	(*Container_Request)(nil),  // 7: Zapuskator.API.v1.Container.Request
	(*Container_Response)(nil), // 8: Zapuskator.API.v1.Container.Response
}
var file_api_v1_proto_depIdxs = []int32{
	5, // 0: Zapuskator.API.v1.Calculate.Request.params:type_name -> Zapuskator.API.v1.Container.Params
	5, // 1: Zapuskator.API.v1.Container.Info.params:type_name -> Zapuskator.API.v1.Container.Params
	0, // 2: Zapuskator.API.v1.Container.Info.status:type_name -> Zapuskator.API.v1.Container.Status
	6, // 3: Zapuskator.API.v1.Container.Response.info:type_name -> Zapuskator.API.v1.Container.Info
	3, // 4: Zapuskator.API.v1.ZapuskatorAPI.Calculate:input_type -> Zapuskator.API.v1.Calculate.Request
	7, // 5: Zapuskator.API.v1.ZapuskatorAPI.GetContainerInfo:input_type -> Zapuskator.API.v1.Container.Request
	4, // 6: Zapuskator.API.v1.ZapuskatorAPI.Calculate:output_type -> Zapuskator.API.v1.Calculate.Response
	8, // 7: Zapuskator.API.v1.ZapuskatorAPI.GetContainerInfo:output_type -> Zapuskator.API.v1.Container.Response
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_proto_init() }
func file_api_v1_proto_init() {
	if File_api_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Calculate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Calculate_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Calculate_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container_Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_proto_goTypes,
		DependencyIndexes: file_api_v1_proto_depIdxs,
		EnumInfos:         file_api_v1_proto_enumTypes,
		MessageInfos:      file_api_v1_proto_msgTypes,
	}.Build()
	File_api_v1_proto = out.File
	file_api_v1_proto_rawDesc = nil
	file_api_v1_proto_goTypes = nil
	file_api_v1_proto_depIdxs = nil
}
