// Code generated by "stringer -type=ContainerStatus -trimprefix=ContainerStatus -output status_string.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContainerStatusNew-0]
	_ = x[ContainerStatusStarting-1]
	_ = x[ContainerStatusRunning-2]
	_ = x[ContainerStatusReady-3]
	_ = x[ContainerStatusNotReady-4]
	_ = x[ContainerStatusUnreachable-5]
	_ = x[ContainerStatusStopping-6]
	_ = x[ContainerStatusStopped-7]
	_ = x[ContainerStatusFailed-8]
}

const _ContainerStatus_name = "NewStartingRunningReadyNotReadyUnreachableStoppingStoppedFailed"

var _ContainerStatus_index = [...]uint8{0, 3, 11, 18, 23, 31, 42, 50, 57, 63}

func (i ContainerStatus) String() string {
	if i < 0 || i >= ContainerStatus(len(_ContainerStatus_index)-1) {
		return "ContainerStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContainerStatus_name[_ContainerStatus_index[i]:_ContainerStatus_index[i+1]]
}
